// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdtcxasZYoK59LKyEfEcxujbVA99POK7E',
    appId: '1:747631481161:web:b5214dc19ad08e707cca98',
    messagingSenderId: '747631481161',
    projectId: 'chat-flutter-7ebd7',
    authDomain: 'chat-flutter-7ebd7.firebaseapp.com',
    storageBucket: 'chat-flutter-7ebd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80MX1-WFLCtgoOc9CpeO3VHNROQS6tC8',
    appId: '1:747631481161:android:6c8c9b2adaed0c3c7cca98',
    messagingSenderId: '747631481161',
    projectId: 'chat-flutter-7ebd7',
    storageBucket: 'chat-flutter-7ebd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvGCFewp9q4afgh389y95JYPhIe0Z--0',
    appId: '1:747631481161:ios:bd9dbc99ece56aac7cca98',
    messagingSenderId: '747631481161',
    projectId: 'chat-flutter-7ebd7',
    storageBucket: 'chat-flutter-7ebd7.appspot.com',
    androidClientId: '747631481161-37vs0e68or88tkaofabimoiksci7l82r.apps.googleusercontent.com',
    iosClientId: '747631481161-0bh05ikc0ta84gi9q25g3mgr9p2dtbfe.apps.googleusercontent.com',
    iosBundleId: 'br.com.jrblog.chatagain',
  );
}
